using System;
using System.Collections.Generic;

namespace OSRCGG
{
    // Каталог хранит таблицы генерации отдельно от алгоритма и UI, чтобы изменения данных
    // не требовали трогать сценарии формы или тестируемые расчеты.
    internal static class CharacterGenerationCatalog
    {

        public static readonly CharacterClassDefinition[] Classes =
        {
            new CharacterClassDefinition("Fighter", "STR", 8, "Human"),
            new CharacterClassDefinition("Explorer", "CON", 6, "Human"),
            new CharacterClassDefinition("Thief", "DEX", 4, "Human"),
            new CharacterClassDefinition("Mage", "INT", 4, "Human"),
            new CharacterClassDefinition("Crusader", "WIL", 6, "Human"),
            new CharacterClassDefinition("Venturer", "CHA", 6, "Human"),
            new CharacterClassDefinition("Assassin", "STR, DEX", 6, "Human"),
            new CharacterClassDefinition("Barbarian", "STR, CON", 8, "Human"),
            new CharacterClassDefinition("Bard", "DEX, CHA", 4, "Human"),
            new CharacterClassDefinition("Bladedancer", "WIL, DEX", 6, "Human"),
            new CharacterClassDefinition("Paladin", "WIL, CHA", 6, "Human"),
            new CharacterClassDefinition("Priestess", "WIL, CHA", 6, "Human"),
            new CharacterClassDefinition("Shaman", "WIL", 4, "Human"),
            new CharacterClassDefinition("Warlock", "INT, WIL", 4, "Human"),
            new CharacterClassDefinition("Witch", "WIL, CHA", 4, "Human"),
            new CharacterClassDefinition("Dwarven Vaultguard", "STR", 8, "Dwarf"),
            new CharacterClassDefinition("Dwarven Craftpriest", "WIL", 6, "Dwarf"),
            new CharacterClassDefinition("Elven Spellsword", "STR, INT", 6, "Elf"),
            new CharacterClassDefinition("Elven Nightblade", "INT, DEX", 4, "Elf"),
            new CharacterClassDefinition("Nobiran Wonderworker", "INT, WIL", 6, "Nobiran"),
            new CharacterClassDefinition("Zaharan Ruinguard", "STR, INT", 6, "Zaharan")
        };

        public static readonly string[] GeneralProficiencies =
        {
            "Adventuring", "Alchemy", "Animal Husbandry", "Animal Training", "Art", "Bargaining",
            "Art/Craft", "Caving", "Collegiate Wizardry", "Craft", "Diplomacy", "Disguise",
            "Driving", "Endurance", "Engineering", "Folkways", "Gambling", "Healing",
            "Intimidation", "Knowledge", "Labor", "Land Surveying", "Language", "Leadership",
            "Lip Reading", "Manual of Arms", "Mapping", "Military Strategy", "Mimicry",
            "Mountaineering", "Naturalism", "Navigation", "Performance", "Profession", "Revelry",
            "Riding", "Seafaring", "Seduction", "Siege Engineering", "Signaling", "Streetwise",
            "Survival", "Swimming", "Theology", "Tracking", "Trapping"
        };

        public static readonly string[] ClassProficiencies =
        {
            "Acrobatics", "Alertness", "Ambushing", "Animal Reflexes", "Arcane Dabbling",
            "Armor Proficiency", "Armor Training", "Battle Magic", "Beast Friendship",
            "Berserkergang", "Black Lore of Zahar", "Blind Fighting", "Bribery",
            "Bright Lore of Aura", "Cat Burglary", "Caving", "Climbing",
            "Collegiate Wizardry", "Combat Ferocity", "Combat Reflexes", "Combat Trickery",
            "Command", "Contemplation", "Contortionism", "Counterspelling", "Disguise",
            "Divine Blessing", "Divine Health", "Dungeonbashing Expertise", "Dwarven Brewing",
            "Eavesdropping", "Elementalism", "Elven Bloodline", "Expanded Repertoire",
            "Experimenting", "Familiar", "Fighting Style Proficiency",
            "Fighting Style Specialization", "Gambling", "Goblin-Slaying",
            "Illusion Resistance", "Intimidation", "Kin-Slaying", "Laying on Hands",
            "Leadership", "Lip Reading", "Lockpicking Expertise", "Loremastery",
            "Magical Engineering", "Magical Music", "Manual of Arms", "Martial Training",
            "Mastery of Conjuration & Summoning", "Mastery of Enchantments & Illusions",
            "Military Strategy", "Mimicry", "Mountaineering", "Mounted Combat",
            "Mystic Aura", "Passing Without Trace", "Poisoning", "Precise Shooting",
            "Prestidigitation", "Prophecy", "Prospecting", "Quiet Magic",
            "Reliquarianism", "Righteous Rebuke", "Running", "Sensing Evil",
            "Sensing Good", "Sensing Power", "Skirmishing", "Skulking", "Sniping",
            "Soothsaying", "Swashbuckling", "Syncretism", "Trapfinding",
            "Transmogrification", "Unarmed Fighting", "Unflappable Casting",
            "Vermin-Slaying", "Wakefulness", "Weapon Finesse", "Weapon Focus",
            "Weapon Proficiency"
        };

        public static readonly Dictionary<string, string> NpcOccupationProficiencies = CreateNpcOccupationProficiencies();

        public static readonly string[] Alignments = { "Lawful", "Neutral", "Chaotic" };
        public static readonly string[] Sexes = { "Male", "Female" };

        public static readonly Dictionary<string, string> AppearanceRu = CreateAppearanceRu();

        private static Dictionary<string, string> CreateAppearanceRu()
        {
            // Таблицы внешности хранят результаты на английском, а этот словарь переводит
            // только пользовательский вывод, не меняя сами броски и сохраненные правила ACKS.
            return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                { "Human", "человек" }, { "Dwarf", "дварф" }, { "Elf", "эльф" }, { "Gnome", "гном" },
                { "Halfling", "халфлинг" }, { "Nobiran", "нобиран" }, { "Zaharan", "захаранец" },

                { "Build", "Телосложение" }, { "Ears", "Уши" }, { "Eyes", "Глаза" }, { "Hands", "Кисти рук" },
                { "Face", "Лицо" }, { "Hair", "Волосы" }, { "Legs", "Ноги" }, { "Mouth", "Рот" },
                { "Nose", "Нос" }, { "Skin", "Кожа" },

                { "Small", "низкое" }, { "Slim", "стройное" }, { "Average", "обычное" },
                { "Broad", "широкое" }, { "Large", "крупное" }, { "Huge", "огромное" },
                { "Thin", "тонкое" }, { "Tall", "высокое" },

                { "Amber", "янтарный" }, { "Auburn", "каштаново-рыжий" }, { "Black", "чёрный" },
                { "Blonde", "светлый" }, { "Blue", "синий" }, { "Blue-Black", "иссиня-чёрный" },
                { "Blue-Grey", "сине-серый" }, { "Blue-Green", "сине-зелёный" },
                { "Brown", "коричневый" }, { "Brown-Black", "коричнево-чёрный" },
                { "Chestnut", "каштановый" }, { "Copper", "медный" }, { "Gold", "золотой" },
                { "Golden", "золотистый" }, { "Green", "зелёный" }, { "Green-Brown", "зелёно-коричневый" },
                { "Green-Grey", "зелёно-серый" }, { "Grey", "серый" }, { "Grey-Brown", "серо-коричневый" },
                { "Hazel", "ореховый" }, { "Ocher", "охристый" }, { "Olive", "оливковый" },
                { "Pale", "бледный" }, { "Platinum", "платиновый" }, { "Red", "рыжий" },
                { "Reddish Brown", "красновато-коричневый" }, { "Rufous", "рыжеватый" },
                { "Sienna", "сиена" }, { "Silver", "серебряный" }, { "Strawberry", "клубничный" },
                { "Violet", "фиолетовый" }, { "White", "белый" }, { "Ivory", "слоновая кость" },
                { "Pure", "чистый" }, { "Snow", "снежный" }, { "Ash", "пепельный" },
                { "Freckled", "веснушчатый" }, { "Ruddy", "румяный" },
                { "Very Light", "очень светлый" }, { "Light", "светлый" }, { "Medium", "средний оттенок" },
                { "Dark", "тёмный" }, { "Very Dark", "очень тёмный" },

                { "Curly", "кудрявые" }, { "Wavy", "волнистые" }, { "Straight", "прямые" },
                { "Tightly curled/kinky", "туго завитые" },

                { "Obese", "тучное" }, { "Hunchback", "горбатое" }, { "Skeletal", "костлявое" },
                { "Crumpled", "помятые" }, { "Missing", "отсутствует" }, { "Torn", "разорванные" },
                { "Bulging", "выпученные" }, { "Cross-eyed", "косоглазие" },
                { "One eye (mass scar tissue)", "один глаз, другой закрыт рубцовой тканью" },
                { "One eye (stitched up)", "один глаз, другой зашит" }, { "Wall-eyed", "расходящееся косоглазие" },
                { "Wandering eyes", "бегающий взгляд" }, { "Misshapen", "деформированные" },
                { "Missing many fingers", "не хватает многих пальцев" },
                { "Badly burned", "сильно обожжённое" }, { "Chinless", "почти без подбородка" },
                { "Disfiguring facial scar", "обезображивающий шрам на лице" },
                { "Patchy facial hair", "неравномерная растительность на лице" },
                { "Wispy facial hair", "редкая растительность на лице" },
                { "Dirty/greasy", "грязные или сальные" }, { "Lank and thin", "жидкие и тонкие" },
                { "Lice-ridden", "с вшами" }, { "Tangled/knotted", "спутанные" },
                { "Club foot", "косолапость" }, { "Constantly drooling", "постоянно пускает слюни" },
                { "Discolored teeth", "потемневшие зубы" }, { "Filed teeth", "подпиленные зубы" },
                { "Frog-like", "лягушачий" }, { "Huge overbite", "сильный верхний прикус" },
                { "Huge underbite", "сильный нижний прикус" }, { "Large buck teeth", "крупные передние зубы" },
                { "Large snaggletooth", "крупный кривой зуб" }, { "Missing many teeth", "не хватает многих зубов" },
                { "Toothless", "беззубый" }, { "Encrusted", "покрыт коркой" }, { "Smashed", "разбитый" },
                { "Warty", "бородавчатый" }, { "Covered in boils", "покрыта нарывами" },
                { "Covered in scarification", "покрыта шрамированием" },
                { "Covered in crude tattoos", "покрыта грубыми татуировками" },
                { "Heavily scarred", "сильно израненная" }, { "Filthy", "грязная" },
                { "Peeling", "шелушащаяся" }, { "Scabrous", "покрыта струпьями" },
                { "Pock marked", "рябая от оспин" },

                { "Barrel-chested", "бочкообразная грудь" }, { "Chubby", "пухлое" },
                { "Skinny", "тощее" }, { "Stocky", "коренастое" }, { "Tiny", "очень маленькое" },
                { "Different colors", "разного цвета" }, { "Narrow", "узкие" },
                { "One eye (eye patch)", "один глаз, второй под повязкой" },
                { "Unusual color", "необычный цвет" }, { "Heavy frown/laugh lines", "глубокие мимические морщины" },
                { "Obvious birthmark", "заметное родимое пятно" }, { "Obvious mole", "заметная родинка" },
                { "Piercing", "пирсинг" }, { "Tattooed", "татуированные" },
                { "Mallen streak", "седая прядь" }, { "Prematurely greying", "преждевременно седеющие" },
                { "Receding/thin", "редеющие" }, { "Callused", "мозолистые" },
                { "Long nails", "длинные ногти" }, { "Missing finger", "не хватает пальца" },
                { "Missing hand (capped)", "нет кисти, культя закрыта колпаком" },
                { "Missing hand (carved prosthetic)", "нет кисти, резной протез" },
                { "Missing hand (hook)", "нет кисти, крюк" }, { "Tattooed knuckles", "татуированные костяшки" },
                { "Peg leg", "деревянная нога" }, { "Short", "короткие" },
                { "Deviated septum", "искривлённая перегородка" }, { "Diastema", "щель между зубами" },
                { "Lip piercing", "пирсинг губы" }, { "Missing tooth", "не хватает зуба" },
                { "Replacement tooth", "вставной зуб" }, { "Thin lips", "тонкие губы" },
                { "Aquiline", "орлиный" }, { "Broken", "сломанный" }, { "Pierced", "проколотый" },
                { "Upturned", "курносый" }, { "Deeply tanned", "сильно загорелая" },
                { "Hirsute", "волосатая" }, { "Minor scars", "небольшие шрамы" },
                { "Unusually pale", "необычно бледная" }, { "Weather-beaten", "обветренная" },

                { "Athletic", "атлетическое" }, { "Broad-chested/bosomy", "широкогрудое/пышногрудое" },
                { "Good posture", "хорошая осанка" }, { "Well-proportioned", "хорошо сложенное" },
                { "Clear", "ясные" }, { "Commanding gaze", "властный взгляд" },
                { "Mesmerizing gaze", "завораживающий взгляд" }, { "Piercing gaze", "проницательный взгляд" },
                { "Striking color", "поразительный цвет" }, { "Graceful", "изящные" }, { "Strong", "сильные" },
                { "Beauty spot", "мушинка" }, { "Dashing facial scar", "эффектный шрам на лице" },
                { "Distinguished features", "выразительные черты" },
                { "Chiseled/fine features", "точёные/тонкие черты" },
                { "Heroic/graceful jawline", "героическая/изящная линия челюсти" },
                { "Honest", "открытое" }, { "Striking/beautifying tattoo", "красивая или выразительная татуировка" },
                { "Youthful countenance", "молодое лицо" }, { "Glossy", "блестящие" },
                { "Lustrous", "сияющие" }, { "Luxurious/silken", "роскошные/шёлковые" },
                { "Long", "длинные" }, { "Muscular/well-toned", "мускулистые/подтянутые" },
                { "Charming/winning smile", "обаятельная улыбка" }, { "Dazzling smile", "ослепительная улыбка" },
                { "Full/sensuous lips", "полные/чувственные губы" }, { "Perfect teeth", "идеальные зубы" },
                { "Flawless", "безупречная" }, { "Healthy complexion", "здоровый цвет лица" }
            };
        }

        private static Dictionary<string, string> CreateNpcOccupationProficiencies()
        {
            return new Dictionary<string, string>()
            {
                {"Barber", "Labor (barbering), Folkways, Revelry, Weapon Proficiency (swords/daggers)"},
                {"Bath Attendant/Masseuse", "Labor (massage), Labor (valeting), Folkways, Revelry"},
                {"Bricklayer", "Labor (bricklaying), Endurance, Folkways, Weapon Proficiency (bludgeons)"},
                {"Cook", "Labor (cooking), Folkways, Revelry, Weapon Proficiency (swords/daggers)"},
                {"Dockworker", "Labor (heaving/stowing), Folkways, Streetwise, Weapon Proficiency (club, hand axe, net, staff)"},
                {"Fuller/Launderer", "Labor (fulling), Labor (laundry), Folkways, Revelry"},
                {"Gondolier/Rower", "Seafaring, Folkways, Revelry, Weapon Proficiency (club, hand axe, net, staff)"},
                {"Gongfarmer/Streetcleaner", "Labor (gongfarming), Endurance, Folkways, Revelry"},
                {"Hawker", "Labor (hawking), Bargaining, Folkways, Revelry"},
                {"Hostler/Stablehand", "Labor (grooming), Driving, Folkways, Riding"},
                {"Maidservant", "Labor (housekeeping), Labor (laundry), Folkways, Revelry"},
                {"Prostitute", "Seduction, Folkways, Revelry, Streetwise"},
                {"Ratcatcher", "Tracking, Trapping, Folkways, Streetwise"},
                {"Roofer/Tiler", "Labor (roofing/tiling), Folkways, Revelry, Weapon Proficiency (bludgeons)"},
                {"Sailor/Fisher", "Seafaring, Labor (heaving/stowing), Revelry, Weapon Proficiency (club, hand axe, net, staff)"},
                {"Scullion", "Labor (scullery), Endurance, Folkways, Revelry"},
                {"Sawyer/Woodcutter", "Labor (woodcutting), Endurance, Fighting Style Proficiency (two-handed weapon), Weapon Proficiency (axes)"},
                {"Teamster", "Driving, Labor (heaving/stowing), Folkways, Streetwise"},
                {"Tavernworker", "Labor (tavernworking), Folkways, Revelry, Streetwise"},
                {"Unskilled Laborer", "Endurance, Folkways, Revelry, Streetwise"},
                {"Bookseller", "Profession (merchant), Craft (scribe), Bargaining, Folkways"},
                {"Chandler/Upholder", "Profession (merchant), Craft (candlemaking), Bargaining, Folkways"},
                {"Coppermonger", "Profession (merchant), Craft (coppersmithing), Bargaining, Folkways"},
                {"Cornmonger", "Profession (merchant), Labor (farming), Bargaining, Folkways"},
                {"Draper", "Profession (merchant), Craft (weaving), Bargaining, Folkways"},
                {"Fishmonger", "Profession (merchant), Labor (fishing), Bargaining, Folkways"},
                {"Fripperer", "Profession (merchant), Craft (tailoring), Bargaining, Folkways"},
                {"Furrier", "Profession (merchant), Trapping, Bargaining, Folkways"},
                {"Greengrocer", "Profession (merchant), Labor (farming), Bargaining, Folkways"},
                {"Horsemonger", "Profession (merchant), Animal Training, Bargaining, Riding"},
                {"Ironmonger", "Profession (merchant), Craft (blacksmithing), Bargaining, Folkways"},
                {"Lawyer", "Profession (lawyer), Bargaining, Diplomacy, Intimidation"},
                {"Lumbermonger", "Profession (merchant), Bargaining, Labor (lumberjacking), Folkways"},
                {"Mercer", "Profession (merchant), Craft (weaving), Bargaining, Folkways"},
                {"Oilmonger", "Profession (merchant), Craft (bottling), Bargaining, Folkways"},
                {"Peltmonger/Skinner", "Profession (merchant), Craft (tanning), Bargaining, Folkways"},
                {"Poulterer", "Profession (merchant), Animal Husbandry, Bargaining, Folkways"},
                {"Salter/Pepperer", "Profession (merchant), Craft (cooking), Bargaining, Folkways"},
                {"Vintner", "Profession (merchant), Craft (winemaking), Bargaining, Folkways"},
                {"Actor", "Performance (acting), Folkways, Streetwise, Weapon Proficiency (swords/daggers)"},
                {"Dancer", "Performance (dance), Folkways, Seduction, Streetwise"},
                {"Musician", "Performance (sing/instrument), Folkways, Revelry, Streetwise"},
                {"Carouser", "Gambling, Folkways, Revelry, Streetwise"},
                {"Apothecary", "Craft (herbalist), Folkways, Naturalism, Revelry"},
                {"Armorer", "Craft (armorsmithing), Folkways, Revelry, Weapon Proficiency (bludgeons)"},
                {"Baker", "Craft (baking), Labor (scullery), Folkways, Revelry"},
                {"Blacksmith", "Craft (blacksmithing), Labor (bellows), Folkways, Weapon Proficiency (bludgeons)"},
                {"Bookbinder", "Craft (bookbinding), Art (embossing), Folkways, Revelry"},
                {"Bowyer/Fletcher", "Craft (fletching), Folkways, Naturalism, Weapon Proficiency (bows/crossbows)"},
                {"Brewer", "Craft (brewing), Labor (milling/mashing), Folkways, Revelry"},
                {"Brickmaker", "Craft (brickmaking), Folkways, Labor (bricklaying), Weapon Proficiency (bludgeons)"},
                {"Butcher", "Labor (butchery), Folkways, Revelry, Weapon Proficiency (swords/daggers)"},
                {"Cabinetmaker", "Craft (cabinetmaking), Folkways, Labor (installation), Weapon Proficiency (axes, bludgeons)"},
                {"Candlemaker", "Craft (candlemaking), Labor (rendering), Folkways, Revelry"},
                {"Capper/Hatter", "Craft (hatting), Art (ornamentation), Folkways, Revelry"},
                {"Carpenter", "Craft (carpentry), Labor (installation), Folkways, Weapon Proficiency (axes, bludgeons)"},
                {"Chaloner/Tapicer", "Craft (upholstering), Labor (heaving/stowing), Folkways, Weapon Proficiency (bludgeons)"},
                {"Clothmaker", "Craft (weaving), Craft (spinning), Folkways, Revelry"},
                {"Cobbler/Cordwainer", "Craft (cobblery), Art (ornamentation), Folkways, Revelry"},
                {"Confectioner", "Craft (confectionary), Labor (scullery), Folkways, Revelry"},
                {"Cooper", "Craft (cooping), Labor (heaving/stowing), Folkways, Revelry"},
                {"Coppersmith", "Craft (coppersmithing), Folkways, Revelry, Weapon Proficiency (bludgeons)"},
                {"Corder/Ropemaker", "Craft (ropemaking), Labor (heaving/stowing), Folkways, Revelry"},
                {"Decorative Artist", "Art (any), Craft (related to art), Folkways, Revelry"},
                {"Florist", "Art (floral arrangement), Folkways, Naturalism, Revelry"},
                {"Gemcutter", "Craft (gemcutting), Art (ornamentation), Bargaining, Folkways"},
                {"Glassworker", "Craft (glassworking), Art (ornamentation), Folkways, Revelry"},
                {"Goldsmith", "Craft (goldsmithing), Art (ornamentation), Bargaining, Folkways"},
                {"Hornworker", "Craft (hornworking), Art (ornamentation), Folkways, Revelry"},
                {"Illuminator", "Art (illumination), Craft (scribe), Folkways, Revelry"},
                {"Jeweler", "Art (jewelry), Craft (goldsmithing or silversmithing), Bargaining, Folkways"},
                {"Locksmith", "Craft (locksmithing), Lockpicking Expertise, Folkways, Streetwise"},
                {"Mason", "Craft (masonry), Endurance, Folkways, Labor (bricklaying)"},
                {"Parchmentmaker", "Craft (parchmentmaking), Labor (butchery), Folkways, Revelry"},
                {"Perfumer", "Craft (perfumery), Folkways, Naturalism, Revelry"},
                {"Potter", "Craft (pottery), Folkways, Revelry"},
                {"Saddler/Fuster", "Craft (saddlery), Folkways, Revelry, Riding"},
                {"Scribe", "Craft (scribe), Art (illumination), Folkways, Revelry"},
                {"Shipwright", "Craft (shipwrighting), Folkways, Seafaring, Siege Engineering"},
                {"Silversmith", "Craft (silversmithing), Bargaining, Folkways, Weapon Proficiency (bludgeons)"},
                {"Spinner", "Craft (spinning), Craft (weaving), Folkways, Revelry"},
                {"Tailor/Seamstress", "Craft (tailoring), Craft (weaving), Folkways, Revelry"},
                {"Tanner/Tawer", "Craft (tanning), Labor (butchery), Folkways, Revelry"},
                {"Taxidermist", "Craft (taxidermy), Labor (butchery), Animal Husbandry, Naturalism"},
                {"Tinker/Toymaker", "Craft (toymaking), Folkways, Performance (puppetry), Revelry"},
                {"Wainwright", "Craft (wainwrighting), Driving, Folkways, Revelry"},
                {"Weaponsmith", "Craft (weaponsmithing), Folkways, Weapon Proficiency (any 2)"},
                {"Wheelwright", "Craft (wheelwrighting), Driving, Folkways, Revelry"},
                {"Cantinakeeper", "Profession (cantinakeeper), Folkways, Labor (cooking), Revelry, Streetwise"},
                {"Tavernkeeper", "Profession (tavernkeeper), Craft (brewing), Folkways, Revelry, Streetwise"},
                {"Innkeeper", "Profession (innkeeper), Craft (brewing), Folkways, Revelry, Streetwise"},
                {"Brothelkeeper", "Profession (brothelkeeper), Folkways, Intimidation, Streetwise, Weapon Proficiency (club, dagger, sap, whip)"},
                {"Almsgiver/Missionary", "Divine Health, Diplomacy, Theology 2"},
                {"Anchorite", "Contemplation, Endurance, Survival, Theology"},
                {"Cultist/Heretic", "Syncretism, Knowledge (occult), Theology, Weapon Proficiency (dagger, dart, staff, whip)"},
                {"Hospitalist/Medician", "Laying on Hands, Healing 2, Theology"},
                {"Inquisitor", "Sensing Evil, Intimidation, Theology, Weapon Proficiency (bludgeons)"},
                {"Oracle", "Prophecy, Performance (storytelling), Theology 2"},
                {"Sacred Courtesan", "Mystic Aura, Performance (dance), Seduction, Theology"},
                {"Seminarian", "Divine Blessing, Theology 2, Weapon Proficiency (bludgeons)"},
                {"Village Witch", "Beast Friendship, Animal Husbandry, Naturalism, Alchemy or Poisoning"},
                {"Apprentice Mage", "Arcane Dabbling, Collegiate Wizardry, Knowledge (history) 2"},
                {"Apprentice Warlock", "Black Lore of Zahar, Knowledge (occultism) 3"},
                {"Astrologer", "Soothsaying, Knowledge (astrology) 3"},
                {"Augur", "Soothsaying, Animal Husbandry, Performance (chanting) 2"},
                {"Charlatan", "Mystic Aura, Alchemy, Bargaining, Folkways"},
                {"Failed Apprentice", "Arcane Dabbling, Collegiate Wizardry, Knowledge (history), Revelry"},
                {"Hedge Magician", "Mastery of Enchantments & Illusions, Healing, Naturalism, Folkways"},
                {"Occultist", "Mastery of Conjuration & Summoning, Knowledge (occultism) 3"},
                {"Prestidigitator", "Prestidigitation, Performance (juggling) 2, Folkways"},
                {"Light Infantry", "Armor Proficiency (light), Fighting Style Proficiency (single weapon, weapon & shield), Manual of Arms, Weapon Proficiency (dagger, javelin, short sword, spear)"},
                {"Heavy Infantry", "Armor Proficiency (heavy), Fighting Style Proficiency (single weapon, weapon & shield), Manual of Arms, Weapon Proficiency (swords/daggers, spears/polearms)"},
                {"Slinger", "Armor Proficiency (light), Fighting Style Proficiency (single weapon, missile), Manual of Arms, Weapon Proficiency (dagger, short sword, sling, sling-staff)"},
                {"Bowman", "Armor Proficiency (light), Fighting Style Proficiency (single weapon, missile), Manual of Arms, Weapon Proficiency (dagger, short sword, short bow, staff)"},
                {"Crossbowman", "Armor Proficiency (medium), Fighting Style Proficiency (single weapon, missile), Manual of Arms, Weapon Proficiency (arbalest, crossbow, dagger, short sword)"},
                {"Longbowman", "Armor Proficiency (medium), Fighting Style Proficiency (single weapon, missile), Manual of Arms, Weapon Proficiency (dagger, long bow, short bow, short sword)"},
                {"Light Cavalry", "Armor Proficiency (light), Fighting Style Proficiency (single weapon, weapon & shield), Manual of Arms, Riding, Weapon Proficiency (swords/daggers, spears/polearms)"},
                {"Horse Archer", "Armor Proficiency (light), Fighting Style Proficiency (single weapon, missile), Manual of Arms, Riding, Weapon Proficiency (bows/crossbows, swords/daggers)"},
                {"Medium Cavalry", "Armor Proficiency (heavy), Fighting Style Proficiency (single weapon, weapon & shield), Manual of Arms, Riding, Weapon Proficiency (spears/polearms, swords/daggers)"},
                {"Heavy Cavalry", "Armor Proficiency (heavy), Fighting Style Proficiency (single weapon, weapon & shield), Manual of Arms, Riding, Weapon Proficiency (spears/polearms, swords/daggers)"},
                {"Cataphract", "Armor Proficiency (heavy), Fighting Style Proficiency (single weapon, missile, weapon & shield), Manual of Arms, Riding, Weapon Proficiency (bows/crossbows, spears/polearms, swords/daggers)"},
                {"Alchemist (apprentice)", "Alchemy 1, Collegiate Wizardry, Labor (scullery), Naturalism"},
                {"Alchemist (assistant)", "Alchemy 2, Collegiate Wizardry, Labor (scullery), Naturalism"},
                {"Alchemist", "Alchemy 3, Collegiate Wizardry, Labor (scullery), Naturalism"},
                {"Animal Trainer (domestic)", "Animal Training 1, Animal Husbandry, Labor (grooming), Riding"},
                {"Animal Trainer (wild)", "Animal Training 2, Animal Husbandry, Labor (grooming), Riding"},
                {"Animal Trainer (giant)", "Animal Training 3, Animal Husbandry, Labor (grooming), Riding"},
                {"Animal Trainer (fantastic)", "Animal Training 4, Animal Husbandry, Labor (grooming), Riding"},
                {"Artillerist", "Siege Engineering, Fighting Style Proficiency (missile), Weapon Proficiency (arbalest, crossbow, sling, sling-staff)"},
                {"Engineer (apprentice)", "Engineering 2, Craft (masonry), Knowledge (mathematics)"},
                {"Engineer (assistant)", "Engineering 3, Craft (masonry), Knowledge (mathematics)"},
                {"Engineer", "Engineering 4, Art (drawing), Craft (masonry), Knowledge (mathematics)"},
                {"Healer", "Healing 1, Naturalism, Folkways, Theology"},
                {"Healer (Physicker)", "Healing 2, Naturalism, Folkways, Theology"},
                {"Healer (Chirugeon)", "Healing 3, Naturalism, Folkways, Theology"},
                {"Marshal (Light Infantry)", "Light Infantry proficiencies, Manual of Arms 2"},
                {"Marshal (Bow)", "Bowman proficiencies, Manual of Arms 2, Weapon Focus (bows & crossbows)"},
                {"Marshal (Heavy Infantry)", "Heavy Infantry proficiencies, Manual of Arms 3"},
                {"Marshal (Light Cavalry)", "Light Cavalry proficiencies, Manual of Arms 2, Mounted Combat"},
                {"Marshal (Heavy Cavalry)", "Heavy Cavalry proficiencies, Manual of Arms 3, Mounted Combat"},
                {"Marshal (Horse Archer)", "Horse Archer proficiencies, Manual of Arms 2, Mounted Combat, Weapon Focus (bows & crossbows)"},
                {"Marshal (Cataphract)", "Cataphract proficiencies, Manual of Arms 3, Mounted Combat, Weapon Focus (bows & crossbows)"},
                {"Navigator", "Navigation, Seafaring 2, Mapping, Weapon Proficiency (club, hand axe, net, staff)"},
                {"Quartermaster", "Light Infantry proficiencies, Profession (quartermaster) 3, Driving"},
                {"Sage (apprentice)", "Magical Engineering 1, Knowledge (chosen field) 1, Collegiate Wizardry, Loremastery"},
                {"Sage (assistant)", "Magical Engineering 2, Knowledge (chosen field) 2, Collegiate Wizardry, Loremastery"},
                {"Sage", "Magical Engineering 3, Knowledge (chosen field) 3, Collegiate Wizardry, Loremastery"},
                {"Scout (Pathfinder)", "Survival, Tracking, Mapping, Navigation"},
                {"Scout (Surveyor)", "Land Surveying, Mapping, Navigation, Survival"},
                {"Siege Engineer", "Siege Engineering 2, Fighting Style Proficiency (missile), Weapon Proficiency (arbalest, crossbow, sling, sling-staff)"},
                {"Ship Captain", "Seafaring 2, Command, Leadership, Weapon Proficiency (club, hand axe, net, staff)"},
                {"Patrician", "Profession (patrician), Diplomacy, Knowledge (law), Riding"}
            };
        }

    }

}

